### ISSUE TITLE
Image format problem

### ISSUE THREAD

**Issue by Orchardseed** [mlandcv/MultiPathGAN#2]
Hi, it looks amazing. 
May I ask does the script also available for other image formats (like tiff.)?
Because in bioimaging analysis the images of different batches may be scaned by different camera and be stored in different image formats. Jpg format is not a common or good format, if you can add OpenSlide may be better.

**Comment by mlandcv** [comment]
The WSI images cannot be loaded as a whole so we tile them up in small patches using python scripts e.g. The one available [here](https://github.com/mlandcv/WSI_Tiling) where the author can take WSI in .svs and .czi formats and tile them up in .jpg/.png etc. format.
